### ISSUE TITLE
qstash Chinese garbled code

### ISSUE THREAD

**Issue by huoyingjianshen** [upstash/qstash-js#88] opened 2024-04-18 05:01 UTC
When there is Chinese characters in the message, the result returned by base64 encryption is garbled: 

"### è§é¢æ é¢ï¼å°ç«çæ»æ¿æ¥è®°ï¼æ¯è¸è¸çåå­¦èå¤§åé©\n\n#### å¼å¥:\n- å¼åºç»é¢ï¼æ¢å¨ä½éå¤´ï¼å".

**Comment by fahreddinozcan** [comment] 2024-05-22 12:25
Hey, can you provide more details about the issue? How can we reproduce this issue?

**Comment by sancar** [comment] 2024-05-22 13:15
We gave support to this on company support channel but let me share my answer here so that others can benefit as well. 

Hi, It looks like qstash works as expected but you need to do some extra hacks on the receiving side.
​
I have found the solution here.
​https://base64.guru/developers/javascript/examples/unicode-strings
​
I have tried returning "chinese华语" from the endpoint and receiving it from the callback.
​
The callback receives body as "Y2hpbmVzZeWNjuivrQ=="
​
If you try to do atob("Y2hpbmVzZeWNjuivrQ==") the response is wrong as you said.
​
But if you follow the suggestion that I have found as follows:
​
decodeURIComponent(escape(atob("Y2hpbmVzZeWNjuivrQ==")));

It returns back the original body 'chinese华语'
​
Closing this issue for now. New readers of the issue or @huoyingjianshen is welcome to reopen an issue if this is not enough. ​

**Closed by sancar** 2024-05-22 13:15 UTC
